apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}

          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 5

          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
