replicaCount: 1

image:
  repository: saydullox/simple-java-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: default

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

autoscaling:
  enabled: false
